[package]
name = "project_management_app_2"
version = "0.13.0"
edition = "2024"

[dependencies]
chrono = "0.4.44"
ron = "0.12.1"
serde = { version = "1.0.228", features = ["derive"] }
rfd = "0.17.2"
eframe = "0.34.3"
egui_extras = { version = "0.34.3", features = ["datepicker"] }
jiff = "0.2.23"
printpdf = "0.9.1"
egui_commonmark = { version = "0.23.0", default-features = false, features = [
    "pulldown_cmark",
] }
