import {
    Button,
    VerticalBox,
    ListView,
    CheckBox,
    LineEdit,
    Spinner,
    TextEdit,
    HorizontalBox,
    ProgressIndicator,
} from "std-widgets.slint";

import {
    EffortByPrjData,
    PjmCallback,
    AppProject,
    DevInfo,
} from "global.slint";
import { Styles } from "styles.slint";

component Separatore inherits Rectangle {
    in property <color> bgcolor;

    height: self.visible == false ? 0px : 1px;
    background: bgcolor;
}

component DevSelectPopup inherits Window {
    in property <[DevInfo]> devs;
    in-out property <int> project;
    in-out property <bool> add;

    public function show(project: int, add: bool) {
        root.add = add;
        root.project = project;
        popup.show();
    }

    popup := PopupWindow {
        close-policy: close-on-click-outside;
        width: 140px;

        Rectangle {
            background: #1e1e1e;
            border-color: #555;
            border-width: 1px;

            VerticalLayout {
                padding: 2px;
                spacing: 1px;

                for dev[dev-idx] in root.devs: Rectangle {
                    height: Styles.height;
                    background: dev.col;
                    border-radius: 2px;

                    Text {
                        color: dev.text-color;
                        text: dev.title;
                        font-weight: 700;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }

                    TouchArea {
                        clicked => {
                            PjmCallback.add_dev_to_project(root.project, dev-idx, root.add);
                            popup.close();
                        }
                    }
                }
            }
        }
    }
}

component Devmenu inherits Window {
    in-out property <int> project;
    in-out property <int> dev;
    in-out property <bool> enable;

    public function show(project: int, dev: int, enable: bool) {
        popup.show();
        root.project = project;
        root.dev = dev;
        root.enable = enable;
    }
    popup := PopupWindow {
        VerticalLayout {
            Rectangle {
                visible: !root.enable;
                background: Colors.grey;
                Text {
                    text: "Add Row";
                }

                TouchArea {
                    clicked => {
                        PjmCallback.add_row(root.project, root.dev);
                        popup.close();
                    }
                }
            }

            Rectangle {
                visible: !root.enable;
                background: Colors.grey;
                Text {
                    text: "Del Row";
                }

                TouchArea {
                    clicked => {
                        PjmCallback.del_row(root.project, root.dev);
                        popup.close();
                    }
                }
            }

            // Rectangle {
            //     background: Colors.grey;
            //     Text {
            //         text: root.enable ? "Show Dev" : "Hide Dev";
            //     }

            //     TouchArea {
            //         clicked => {
            //             PjmCallback.hide_dev(root.project, root.dev, root.enable);
            //             popup.close();
            //         }
            //     }
            // }
        }

        x: 20px;
        y: 20px;
        close-policy: close-on-click-outside;
    }
}

export component LeftColumn inherits Rectangle {
    in property <AppProject> app_project;
    in-out property <length> viewport_y;

    width: Styles.left-column-width;

    popup := Devmenu {
        visible: false;
    }

    dev-popup := DevSelectPopup {
        devs: root.app_project.devs;
        visible: false;
    }

    Flickable {
        width: root.width;
        height: root.height;
        viewport-y <=> root.viewport_y;
        VerticalLayout {
            spacing: 0px;
            padding: 0px;
            // Per ogni progetto
            for project in root.app_project.projects: Rectangle {
                visible: project.visible && project.enable;
                height: self.visible ? self.preferred-height : 0px;
                VerticalLayout {
                    spacing: 0px;
                    padding: 0px;
                    // Casella di testo per l'info del progetto
                    // + i vari Dev
                    Rectangle {
                        // Casella di testo per l'info del progetto
                        // + i vari Dev
                        HorizontalLayout {
                            spacing: 0px;
                            padding: 0px;
                            // Casella di testo per l'info del progetto
                            // + il pulsante "+ Dev"
                            VerticalLayout {
                                spacing: 0px;
                                padding: 0px;

                                Rectangle {
                                    TextEdit {
                                        wrap: TextWrap.word-wrap;
                                        horizontal-alignment: center;
                                        text: project.text;
                                        width: parent.width;
                                        font-family: Styles.font-family;
                                        font-size: Styles.font-size;
                                        height: root.visible ? parent.height : 0px;

                                        edited(text) => {
                                            project.text = text;
                                            PjmCallback.changed = true;
                                            PjmCallback.set_project_name(project.project_id, text);
                                        }
                                    }
                                }

                                HorizontalLayout {
                                    spacing: 0px;
                                    padding: 0px;

                                    add-dev-btn := Rectangle {
                                        height: root.visible ? Styles.height : 0px;
                                        background: add-dev-ta.has-hover ? #3a3a3a : #2a2a2a;
                                        border-color: #555;
                                        border-width: 1px;

                                        Text {
                                            text: "+ Dev";
                                            color: Colors.lightgray;
                                            font-size: Styles.font-size;
                                            font-family: Styles.font-family;
                                            horizontal-alignment: center;
                                            vertical-alignment: center;
                                            height: root.visible ? Styles.height : 0px;
                                        }

                                        add-dev-ta := TouchArea {
                                            height: parent.height;
                                            width: parent.width;
                                            visible: root.visible;
                                            clicked => {
                                                dev-popup.x = add-dev-btn.absolute-position.x;
                                                dev-popup.y = add-dev-btn.absolute-position.y + add-dev-btn.height;
                                                dev-popup.show(project.project_id, true);
                                            }
                                        }
                                    }

                                    del-dev-btn := Rectangle {
                                        height: root.visible ? Styles.height : 0px;
                                        background: del-dev-ta.has-hover ? #3a3a3a : #2a2a2a;
                                        border-color: #555;
                                        border-width: 1px;

                                        Text {
                                            text: "- Dev";
                                            color: Colors.lightgray;
                                            font-size: Styles.font-size;
                                            font-family: Styles.font-family;
                                            horizontal-alignment: center;
                                            vertical-alignment: center;
                                            height: root.visible ? Styles.height : 0px;
                                        }

                                        del-dev-ta := TouchArea {
                                            height: parent.height;
                                            width: parent.width;
                                            visible: root.visible;

                                            clicked => {
                                                dev-popup.x = del-dev-btn.absolute-position.x;
                                                dev-popup.y = del-dev-btn.absolute-position.y + del-dev-btn.height;
                                                dev-popup.show(project.project_id, false);
                                            }
                                        }
                                    }
                                }
                            }

                            // I vari dev collegati al progetto
                            VerticalLayout {
                                spacing: 0px;
                                padding: 0px;
                                for data in project.devs-of-the-project: Rectangle {
                                    property <bool> visibility;
                                    visibility: data.visible;
                                    // I vari dev collegati al progetto
                                    VerticalLayout {
                                        spacing: 0px;
                                        padding: 0px;
                                        Separatore {
                                            bgcolor: root.app_project.devs[data.dev].col;
                                            height: visibility ? Styles.dev-border : 0px;
                                        }

                                        Rectangle {
                                            height: visibility ? Styles.height * (data.max + 1) : 0px;

                                            HorizontalLayout {
                                                spacing: 0px;
                                                padding: 0px;
                                                // Text Dev1 or Dev2, ...
                                                Rectangle {
                                                    background: root.app_project.devs[data.dev].col;
                                                    width: Styles.width;
                                                    clip: true;
                                                    Text {
                                                        width: Styles.width - 10px;
                                                        font-weight: 800;
                                                        color: root.app_project.devs[data.dev].text-color;
                                                        text: root.app_project.devs[data.dev].title;
                                                        horizontal-alignment: center;
                                                        vertical-alignment: center;
                                                        wrap: word-wrap;
                                                        cell := TouchArea {
                                                            width: parent.width;
                                                            height: parent.height;
                                                            double-clicked => {
                                                                debug("add_row");
                                                                PjmCallback.add_row(project.project_id, data.dev);
                                                            }

                                                            pointer-event(event) => {
                                                                if event.button == PointerEventButton.right {
                                                                    if event.kind == PointerEventKind.down {
                                                                        popup.x = cell.absolute-position.x;
                                                                        popup.y = cell.absolute-position.y;
                                                                        popup.visible = true;
                                                                        popup.show(project.project_id, data.dev, !data.enable);
                                                                    } else {
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }

                                                Rectangle {
                                                    height: visibility ? Styles.height * (data.max + 1) : 0px;
                                                    width: Styles.width - 25px;
                                                    VerticalLayout {
                                                        spacing: 0px;
                                                        padding: 0px;
                                                        LineEdit {
                                                            horizontal-alignment: center;
                                                            text: data.effort;
                                                            height: Styles.height;

                                                            accepted(text) => {
                                                                data.effort = text.to-float();
                                                                PjmCallback.set_dev_effort(project.project_id, data.dev, text.to-float());
                                                            }
                                                        }

                                                        Rectangle {
                                                            background: ((data.remains == data.effort && data.effort != 0) || (data.remains < 0)) ? Colors.red : Colors.transparent;
                                                            height: visibility ? self.preferred-height : 0px;
                                                            Text {
                                                                height: visibility ? self.preferred-height : 0px;
                                                                horizontal-alignment: center;
                                                                vertical-alignment: center;
                                                                text: data.remains;
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }

                                        Separatore {
                                            height: visibility ? Styles.dev-border : 0px;
                                            bgcolor: root.app_project.devs[data.dev].col;
                                        }
                                    }
                                }
                            }
                        }
                    }

                    Rectangle {
                        height: root.visible ? Styles.dev-border : 0px;
                        background: Styles.color-between-projects;
                    }
                }
            }
        }
    }
}
