import {
    EffortByPrjGui,
    AppProject,
} from "global.slint";

export component RightColumn inherits Rectangle {
    in property <string> prefix;
    in property <AppProject> app_project;
    in-out property <length> viewport_y;
    in-out property <length> viewport_x;

    Flickable {
        width: root.width;
        height: root.height;

        viewport-y <=> root.viewport_y;
        viewport-x <=> root.viewport_x;
        VerticalLayout {
            padding: 0px;
            spacing: 0px;
            for project in root.app_project.projects: EffortByPrjGui {
                project: project;
                devs: root.app_project.devs;
            }
        }
    }
}
