import {
    EffortByPrjGui,
    AppProject,
    DayData,
    PjmCallback,
} from "global.slint";
import { Styles } from "styles.slint";
import { StyleMetrics, HorizontalBox } from "std-widgets.slint";

export component RightFooter inherits Rectangle {
    in property <AppProject> app_project;
    in-out property <length> viewport-x;

    Flickable {
        viewport-x <=> root.viewport-x;
        HorizontalLayout {
            padding: 0px;
            spacing: 0px;
            for data in root.app_project.sovra: Rectangle {
                HorizontalLayout {
                    Rectangle {
                        background: data.week == PjmCallback.this_week ? Styles.this-week-color : Colors.transparent;
                        width: data.week == PjmCallback.this_week ? PjmCallback.this_week_width : 0px;
                    }

                    VerticalLayout {
                        for value[index] in data.value: Rectangle {
                            property <bool> worker-visible: PjmCallback.last-search == "" || root.app_project.worker_names[index] == PjmCallback.last-search;
                            background: index.mod(2) == 0 ? Colors.gray : Colors.black;
                            width: Styles.width;
                            height: worker-visible ? Styles.height : 0px;
                            visible: worker-visible;
                            Text {
                                font-weight: value == 80 ? 200 : 800;
                                color: value > 80 ? Colors.red : (value < 40 ? Colors.yellow : (value < 80 ? Colors.orange : Colors.lightgreen));
                                text: value;
                            }
                        }
                    }
                }
            }
        }
    }
}
