export global Styles {
    out property <length> font-size: 16px;
    out property <length> width: 90px;
    out property <length> height: 18px;
    out property <string> font-family: "Courier New";
    out property <length> left-column-width: 300px;
    out property <length> dev-border: 3px;
    out property <color> color-between-projects: Colors.gray;
    out property <color> color-start-stop: Colors.yellow;
    out property <color> note-color: Colors.yellow;
}
