export global Styles {
    out property <int> default-max-hours: 40;
    out property <length> font-size: 16px;
    out property <length> width: 90px;
    out property <length> height: 18px;
    out property <string> font-family: "Menlo, Consolas, SF Mono, Courier New";
    out property <length> left-column-width: 300px;
    out property <length> dev-border: 3px;
    out property <color> color-between-projects: Colors.gray;
    out property <color> color-start-stop: Colors.yellow;
    out property <color> note-color: Colors.orange;
    out property <color> effort-color: Colors.orange;
    out property <color> this-week-color: #00ce3a;
}
